var a: number = 10;
var b: number = 15;
var add = a+b;
console.log("Addition of two numbers",+add);
var sub = a-b;
console.log("Subtraction of two numbers",+sub);
var mul = a*b;
console.log("Multiplication of two numbers",+mul);
var div = a/b;
console.log("Division of two numbers",+div);